name: 定期的に冷凍庫の温度をチェックする

on:
- workflow_dispatch
- schedule: 
    cron:  '0,10,20,30,40,50 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i -g bun
    - run: bun i
    - run: bun run index.ts
